### ISSUE TITLE
Is `nuxt-schema-org` superseded by `@unhead/schema-org`?

### ISSUE THREAD

**Issue by eddybrando** [harlan-zw/nuxt-schema-org#24]
### Details

In your [documentation page about the Nuxt integration](https://unhead-schema-org.harlanzw.com/integrations/nuxt/module) it says to use the `nuxt-schema-org` package.

However, in [Nuxt's modules page](https://nuxt.com/modules/schema-org#new-package) it says:

> The package `@vueuse/schema-org` (which used `nuxt-schema-org`) has been superseded by [@unhead/schema-org](https://github.com/harlan-zw/unhead-schema-org) which offers the same simple API.
> This package will continue to mirror the API for the foreseeable future.
> It's recommended to use `@unhead/schema-org` for new projects.

My understanding is that we should use now `@unhead/schema-org` for Nuxt as well. Can you confirm this? And if so, should there be an update to your documentation to point to the new package?

**Comment by AlejandroAkbal** [comment]
I have the same question, it's unclear where to use the nuxt integration as it seems to fail

**Comment by professorhaseeb** [comment]
This [doc](https://nuxt.com/modules/schema-org) is outdated.


this doc is working: https://unhead-schema-org.harlanzw.com/integrations/nuxt/module

**Comment by harlan-zw** [comment]
Working on improving the docs, thanks for flagging

**Comment by harlan-zw** [comment]
Sorry for not answering the initial question. The issue is that the Nuxt modules page is linking to the wrong read me file, it's pointing to `@vueuse/schema-org` (which has been superseded by `@unhead/schema-org`). This actually has no bearing on the Nuxt module as the underlying API doesn't really matter. 

I'll fix the Nuxt modules link to point to this repo (now `nuxt-schema-org`) and read me which should clear up the confusion.

Official docs for Nuxt are now at https://nuxtseo.com/schema-org/getting-started/installation which I'll be improving as I go.

Please let me know if you have any further questions
