### ISSUE TITLE
docs: URL to Unheads identity guide changed

### ISSUE THREAD

**Issue by riddla** [harlan-zw/nuxt-schema-org#34]
### Additional context

As Unhead seem to have restructured their docs, the link to https://unhead.unjs.io/schema-org/guides/identity over at https://nuxtseo.com/schema-org/guides/full-documentation fails. Should it be https://unhead.unjs.io/schema-org/recipes/identity now?

**Comment by riddla** [comment]
PS: Would have loved to a PR for this, are your docs somewhere on Github?

**Comment by harlan-zw** [comment]
Hey, thanks for the issue.

The docs are here if you'd like to do a PR https://github.com/harlan-zw/nuxt-seo-kit/edit/v2/docs/content/4.schema-org/2.guides/0.quick-setup.md, would be appreciated:pray: :) 

Otherwise, happy to fix it myself.

(the docs being outside the repo is something I hope to fix at some point)

**Comment by riddla** [comment]
You're welcome. See https://github.com/harlan-zw/nuxt-seo-kit/pull/115 :)
